/**
 * Data version - updated when Statpedia source data is imported
 *
 * This file is auto-generated by scripts/parse-statpedia.ts
 * DO NOT EDIT MANUALLY
 */
export const DATA_VERSION = '2026-01-25';
